---
# tasks file for mdarke.php7

- name: Add the PHP repository
  apt_repository: repo="{{ php_enablerepo }}"
  when: php_enablerepo is defined

- name: install php packages
  apt: pkg={{ item }} state=present
  with_items: "{{ php_packages }}"

#- name: install php-xdebug
#  apt: pkg=php-xdebug state=present
